Correção/adição de instruções
ResidenciaTICBrisa/03_Robotica pull request #12
Opened 2023-08-09 13:38 UTC by Gustavo-Macedo1

- Correção de arquivos de instrução anteriores (ROS1 e Robot Settings)
- Criação de tutorial de instalação e configuração de VMs com Virt Manager
- Criação de tutorial de instalação do SDK de C++

2023-08-09 18:49 UTC, DaviAntonio requested changes
Verificar a necessidade de usar o `pip` do Python 2 e de adicionar o repositório do ROS1.

2023-08-09 18:49 UTC, DaviAntonio commented on docs/Instruções/CPP_SDK.md
> +sudo apt install build-essential cmake python3-pip
Se o python suportado é o 2, o pacote deve ser o `python-pip`. Ele vai ser chamado na linha de comando como `pip2`. O comando `pip` normalmente vai executar o `pip2`.

2023-08-09 18:49 UTC, DaviAntonio commented on docs/Instruções/ROS1.md
>  sudo apt install ros-noetic-NOME_DO_PACOTE
Para fazer isso é necessário adicionar o repositório do ROS1, ou o pacote não será encontrado.

2023-08-14 20:10 UTC, DaviAntonio requested changes
Revisar instruções considerando que são para o NAOv6 e que o ambiente de desenvolvimento exige Python 2.

2023-08-14 20:10 UTC, DaviAntonio commented on docs/Instruções/CPP_SDK.md
> +# Instalação do SDK de C++
Deixar claro que o guia é para o NAOv6

2023-08-14 20:10 UTC, DaviAntonio commented on docs/Instruções/CPP_SDK.md
> +sudo apt install build-essential cmake python3-pip
A documentação do NAOv6 exige Python2 e Ubuntu 16.04.
http://doc.aldebaran.com/2-8/dev/python/install_guide.html

O pacote a ser instalado é `python-pip`.

Para instalar outros pacotes é necessário atualizar para a última versão que suporta Python 2:
`pip install 'pip==20.3.4'`.

2023-08-14 20:10 UTC, DaviAntonio commented on docs/Instruções/CPP_SDK.md
> +PATH=$PATH:$HOME/.local/bin
Não é necessário adicionar o caminho ao `PATH` em uma instalação do Ubuntu 16.04

2023-08-14 20:10 UTC, DaviAntonio commented on docs/Instruções/CPP_SDK.md
> +> Obs.: **NÃO ATUALIZAR PIP** (o suporte do pip ao Python 2 chegou ao fim, sua atualização corrompe o Python 2 do sistema);
É recomendável atualizar para a última versão com suporte a Python 2: `pip install pip==20.3.4'`

2023-08-14 20:10 UTC, DaviAntonio commented on docs/Instruções/Maquina_Virtual.md
> +Os robôs NAO utilizam diversos programas para configuração, programação e manutenção. Porém, esses programas são compatíveis com diferentes versões do sistema Linux.
Deixar claro que é o NAOv6

2023-08-14 20:10 UTC, DaviAntonio commented on docs/Instruções/Maquina_Virtual.md
> +| Robot Settings | Ubuntu 16.04 |
Colocar as versões dos programas para o NAOv6:
- Robot Settings 2.8.6
- Coreograph 2.8.6
- PyNAOqi SDK 2.8.6
- NAOqi SDK 2.8.5
- Flasher 2.1.0

2023-08-15 22:40 UTC, Gustavo-Macedo1 commented on docs/Instruções/CPP_SDK.md
> +sudo apt install build-essential cmake python3-pip
O pacote python-pip estava com problemas para instalar pacotes. Com a atualização para o pip 20.3.4, foi possível instalar o qiBuild com sucesso.

2023-08-15 22:42 UTC, Gustavo-Macedo1 commented on docs/Instruções/CPP_SDK.md
> +# Instalação do SDK de C++
Revisado e alterado.

2023-08-15 22:42 UTC, Gustavo-Macedo1 commented on docs/Instruções/CPP_SDK.md
> +PATH=$PATH:$HOME/.local/bin
Revisado, testado e alterado.

- O caminho realmente não era necessário.

2023-08-15 22:46 UTC, Gustavo-Macedo1 commented on docs/Instruções/CPP_SDK.md
> +> Obs.: **NÃO ATUALIZAR PIP** (o suporte do pip ao Python 2 chegou ao fim, sua atualização corrompe o Python 2 do sistema);
A atualização automática sugerida pelo pip no terminal não deve ser feita, pois corrompe o pip2 e o pip3. Entretanto, a atualização manual para a versão 20.3.4 foi testada e obteve sucesso.
- A atualização manual para o pip 20.3.4 foi adicionada como passo necessário da instalação do qiBuild.

2023-08-15 22:49 UTC, Gustavo-Macedo1 commented on docs/Instruções/Maquina_Virtual.md
> +Os robôs NAO utilizam diversos programas para configuração, programação e manutenção. Porém, esses programas são compatíveis com diferentes versões do sistema Linux.
Foi entendido que o guia parece se referir apenas ao NAO v6.

- Foi realizado a atualização do guia para se tornar genérico, usando os programas do NAO v6 apenas como exemplo e adicionando uma observação referente ao NAO v4.

2023-08-15 22:56 UTC, Gustavo-Macedo1 commented on docs/Instruções/Maquina_Virtual.md
> +| Robot Settings | Ubuntu 16.04 |
O NAO Flasher não possui compatibilidade atual bem definida na documentação oficial, sugerindo apenas, em um guia mais antigo, que o NAO Flasher é multi-plataforma, mas apenas compatível com o NAO v4. Aparentemente o NAO v6 utiliza os recursos do NAO Flasher no próprio Choregraphe.

- Os demais programas tiveram suas versões adicionadas à tabela.

2023-08-16 03:56 UTC, closed without merging